/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    people: Person;
    partners: Partner;
    programmes: Programme;
    projects: Project;
    events: Event;
    'success-stories': SuccessStory;
    articles: Article;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'success-stories': SuccessStoriesSelect<false> | SuccessStoriesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents':
      PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Assigned platform governance and content access roles.
   */
  roles?: ('admin' | 'editor' | 'reviewer' | 'media_manager')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Crucial for accessibility (WCAG 2.2 AA) and image SEO. Describe the visual content.
   */
  alt: string;
  /**
   * Descriptive title for internal search and media library organization.
   */
  title?: string | null;
  /**
   * Editorial caption displayed below the media item in stories and galleries.
   */
  caption?: string | null;
  mediaType?: ('image' | 'document' | 'video') | null;
  attribution?: {
    /**
     * Name of the photographer, agency, or originating source.
     */
    photographerOrSource?: string | null;
    /**
     * Rights constraints or creative license details.
     */
    copyrightNotes?: string | null;
  };
  /**
   * Geographic location where photo/video was captured (e.g., Benin City, Lagos, Abuja).
   */
  location?: string | null;
  /**
   * Historical date when the asset was originally captured.
   */
  dateCaptured?: string | null;
  /**
   * Tags for categorization (e.g., #DigitalSkills, #WomenInTech, #Graduation2026).
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional embedded video link for streamable assets.
   */
  externalVideoUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  fullName: string;
  /**
   * Unique URL identifier. Auto-generated from "fullName" if not specified.
   */
  slug?: string | null;
  /**
   * Official position (e.g., Founder & CEO, Lead Technical Instructor, Board Advisor).
   */
  role: string;
  organization?: string | null;
  /**
   * e.g., Executive Leadership, Technology & Innovation, TVET Programmes.
   */
  division?: string | null;
  profileImage?: (number | null) | Media;
  /**
   * Brief 2-3 sentence introductory biography for cards and speaker profiles.
   */
  shortBio?: string | null;
  /**
   * Comprehensive biographical and impact background.
   */
  fullBio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  designations?: {
    isLeadership?: boolean | null;
    isBoardMember?: boolean | null;
    isTeamMember?: boolean | null;
    isFacilitator?: boolean | null;
    isSpeaker?: boolean | null;
    isAuthor?: boolean | null;
  };
  socialLinks?: {
    linkedin?: string | null;
    twitter?: string | null;
    instagram?: string | null;
    website?: string | null;
  };
  contactInfo?: {
    email?: string | null;
    showEmailPublicly?: boolean | null;
    phone?: string | null;
    showPhonePublicly?: boolean | null;
  };
  /**
   * Lower numbers appear first (e.g., 1 for Founder/CEO).
   */
  displayOrder?: number | null;
  status?: ('active' | 'alumni' | 'inactive') | null;
  /**
   * Configure search engine metadata, Open Graph preview, and indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50-60 characters. Appears in search results and browser tabs.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150-160 characters. Concise summary of the page for search snippets.
     */
    metaDescription?: string | null;
    /**
     * Recommended dimension: 1200 × 630 pixels.
     */
    metaImage?: (number | null) | Media;
    /**
     * Check to prevent web crawlers from indexing this item.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  /**
   * Unique URL identifier. Auto-generated from "name" if not specified.
   */
  slug?: string | null;
  /**
   * Transparent PNG or SVG logo preferred.
   */
  logo: number | Media;
  website?: string | null;
  partnerType:
    | 'international_development'
    | 'donor'
    | 'government'
    | 'ngo'
    | 'corporate'
    | 'academic_research'
    | 'investor'
    | 'media'
    | 'community_organization'
    | 'other';
  relationshipType?:
    | (
        | 'strategic_partner'
        | 'funding_partner'
        | 'implementing_partner'
        | 'technical_partner'
        | 'ecosystem_partner'
      )
    | null;
  /**
   * Brief overview of the partnership collaboration and institutional synergy.
   */
  description?: string | null;
  timeline?: {
    /**
     * e.g., 2020
     */
    startYear?: number | null;
    endYear?: number | null;
  };
  isFeatured?: boolean | null;
  /**
   * Configure search engine metadata, Open Graph preview, and indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50-60 characters. Appears in search results and browser tabs.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150-160 characters. Concise summary of the page for search snippets.
     */
    metaDescription?: string | null;
    /**
     * Recommended dimension: 1200 × 630 pixels.
     */
    metaImage?: (number | null) | Media;
    /**
     * Check to prevent web crawlers from indexing this item.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes".
 */
export interface Programme {
  id: number;
  title: string;
  /**
   * Unique URL identifier. Auto-generated from "title" if not specified.
   */
  slug?: string | null;
  /**
   * Concise summary for programme cards, catalogue views, and search previews.
   */
  shortDescription: string;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  programmeType:
    | 'digital_skills'
    | 'vocational_tvet'
    | 'entrepreneurship'
    | 'migration_reintegration'
    | 'women_empowerment'
    | 'youth_employment'
    | 'leadership_governance'
    | 'other';
  focusAreas?:
    | {
        skill: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g., Unemployed youth, returning migrants, female entrepreneurs, tech enthusiasts.
   */
  targetAudience?: string | null;
  deliveryFormat?: ('in_person' | 'virtual' | 'hybrid') | null;
  locations?:
    | {
        location: string;
        id?: string | null;
      }[]
    | null;
  schedule?: {
    startDate?: string | null;
    endDate?: string | null;
    isOngoing?: boolean | null;
  };
  applicationStatus?: ('open' | 'upcoming' | 'closed' | 'by_invitation') | null;
  /**
   * Internal registration route or external portal endpoint.
   */
  applicationUrl?: string | null;
  heroMedia?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  partners?: (number | Partner)[] | null;
  impactStatistics?:
    | {
        metricValue: string;
        metricLabel: string;
        metricDescription?: string | null;
        id?: string | null;
      }[]
    | null;
  isFeatured?: boolean | null;
  status?: ('draft' | 'published' | 'archived') | null;
  /**
   * Configure search engine metadata, Open Graph preview, and indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50-60 characters. Appears in search results and browser tabs.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150-160 characters. Concise summary of the page for search snippets.
     */
    metaDescription?: string | null;
    /**
     * Recommended dimension: 1200 × 630 pixels.
     */
    metaImage?: (number | null) | Media;
    /**
     * Check to prevent web crawlers from indexing this item.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Unique URL identifier. Auto-generated from "title" if not specified.
   */
  slug?: string | null;
  /**
   * Concise summary of the intervention, target beneficiaries, and overarching purpose.
   */
  summary: string;
  fullContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The broader institutional programme this specific project operationalizes.
   */
  parentProgramme?: (number | null) | Programme;
  partners?: (number | Partner)[] | null;
  locations?:
    | {
        location: string;
        id?: string | null;
      }[]
    | null;
  timeline?: {
    startDate?: string | null;
    endDate?: string | null;
  };
  projectStatus?: ('planned' | 'active' | 'completed' | 'on_hold') | null;
  beneficiaryMetrics?:
    | {
        metricName: string;
        metricValue: string;
        unitOrContext?: string | null;
        id?: string | null;
      }[]
    | null;
  fundingAndSupport?: {
    donorOrFunder?: string | null;
    grantDetails?: string | null;
  };
  heroMedia?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  outcomes?: string | null;
  reportsAndDocuments?: (number | Media)[] | null;
  isFeatured?: boolean | null;
  /**
   * Configure search engine metadata, Open Graph preview, and indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50-60 characters. Appears in search results and browser tabs.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150-160 characters. Concise summary of the page for search snippets.
     */
    metaDescription?: string | null;
    /**
     * Recommended dimension: 1200 × 630 pixels.
     */
    metaImage?: (number | null) | Media;
    /**
     * Check to prevent web crawlers from indexing this item.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Unique URL identifier. Auto-generated from "title" if not specified.
   */
  slug?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  eventType:
    | 'workshop'
    | 'summit'
    | 'hackathon'
    | 'exhibition'
    | 'webinar'
    | 'meetup'
    | 'ceremony'
    | 'other';
  format?: ('in_person' | 'virtual' | 'hybrid') | null;
  schedule: {
    startDateTime: string;
    endDateTime?: string | null;
    timezone?: string | null;
  };
  venue?: {
    venueName?: string | null;
    address?: string | null;
    city?: string | null;
    country?: string | null;
  };
  onlineAccess?: {
    meetingUrl?: string | null;
    accessInstructions?: string | null;
  };
  speakers?: (number | Person)[] | null;
  partners?: (number | Partner)[] | null;
  relatedProgramme?: (number | null) | Programme;
  relatedProject?: (number | null) | Project;
  heroMedia?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  status?: ('draft' | 'published' | 'postponed' | 'cancelled' | 'completed') | null;
  /**
   * Configure search engine metadata, Open Graph preview, and indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50-60 characters. Appears in search results and browser tabs.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150-160 characters. Concise summary of the page for search snippets.
     */
    metaDescription?: string | null;
    /**
     * Recommended dimension: 1200 × 630 pixels.
     */
    metaImage?: (number | null) | Media;
    /**
     * Check to prevent web crawlers from indexing this item.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories".
 */
export interface SuccessStory {
  id: number;
  /**
   * Compelling headline (e.g., "From Unemployed Graduate to Leading UI/UX Designer in Edo State").
   */
  title: string;
  /**
   * Unique URL identifier. Auto-generated from "title" if not specified.
   */
  slug?: string | null;
  beneficiaryName: string;
  /**
   * e.g., Founder at StitchLab Hub, Junior Software Engineer at TechCorp.
   */
  beneficiaryRole?: string | null;
  location?: string | null;
  relatedProgramme?: (number | null) | Programme;
  relatedProject?: (number | null) | Project;
  /**
   * Highlighted pull-quote for impact cards and hero showcases.
   */
  quote?: string | null;
  summary?: string | null;
  fullStory?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroMedia?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  impactMetrics?:
    | {
        metricValue: string;
        metricLabel: string;
        id?: string | null;
      }[]
    | null;
  storyDate?: string | null;
  isFeatured?: boolean | null;
  status?: ('draft' | 'published' | 'archived') | null;
  /**
   * Configure search engine metadata, Open Graph preview, and indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50-60 characters. Appears in search results and browser tabs.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150-160 characters. Concise summary of the page for search snippets.
     */
    metaDescription?: string | null;
    /**
     * Recommended dimension: 1200 × 630 pixels.
     */
    metaImage?: (number | null) | Media;
    /**
     * Check to prevent web crawlers from indexing this item.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Unique URL identifier. Auto-generated from "title" if not specified.
   */
  slug?: string | null;
  /**
   * Short teaser displayed in news grids, newsletters, and search snippets.
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  authors?: (number | Person)[] | null;
  category: 'insights' | 'news' | 'case_study' | 'research' | 'community';
  publishedAt?: string | null;
  heroMedia?: (number | null) | Media;
  relatedProgrammes?: (number | Programme)[] | null;
  relatedProjects?: (number | Project)[] | null;
  relatedEvents?: (number | Event)[] | null;
  status?: ('draft' | 'published' | 'archived') | null;
  /**
   * Configure search engine metadata, Open Graph preview, and indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50-60 characters. Appears in search results and browser tabs.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150-160 characters. Concise summary of the page for search snippets.
     */
    metaDescription?: string | null;
    /**
     * Recommended dimension: 1200 × 630 pixels.
     */
    metaImage?: (number | null) | Media;
    /**
     * Check to prevent web crawlers from indexing this item.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'programmes';
        value: number | Programme;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'success-stories';
        value: number | SuccessStory;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  title?: T;
  caption?: T;
  mediaType?: T;
  attribution?:
    | T
    | {
        photographerOrSource?: T;
        copyrightNotes?: T;
      };
  location?: T;
  dateCaptured?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  externalVideoUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  fullName?: T;
  slug?: T;
  role?: T;
  organization?: T;
  division?: T;
  profileImage?: T;
  shortBio?: T;
  fullBio?: T;
  designations?:
    | T
    | {
        isLeadership?: T;
        isBoardMember?: T;
        isTeamMember?: T;
        isFacilitator?: T;
        isSpeaker?: T;
        isAuthor?: T;
      };
  socialLinks?:
    | T
    | {
        linkedin?: T;
        twitter?: T;
        instagram?: T;
        website?: T;
      };
  contactInfo?:
    | T
    | {
        email?: T;
        showEmailPublicly?: T;
        phone?: T;
        showPhonePublicly?: T;
      };
  displayOrder?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  website?: T;
  partnerType?: T;
  relationshipType?: T;
  description?: T;
  timeline?:
    | T
    | {
        startYear?: T;
        endYear?: T;
      };
  isFeatured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  fullDescription?: T;
  programmeType?: T;
  focusAreas?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  targetAudience?: T;
  deliveryFormat?: T;
  locations?:
    | T
    | {
        location?: T;
        id?: T;
      };
  schedule?:
    | T
    | {
        startDate?: T;
        endDate?: T;
        isOngoing?: T;
      };
  applicationStatus?: T;
  applicationUrl?: T;
  heroMedia?: T;
  gallery?: T;
  partners?: T;
  impactStatistics?:
    | T
    | {
        metricValue?: T;
        metricLabel?: T;
        metricDescription?: T;
        id?: T;
      };
  isFeatured?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  fullContent?: T;
  parentProgramme?: T;
  partners?: T;
  locations?:
    | T
    | {
        location?: T;
        id?: T;
      };
  timeline?:
    | T
    | {
        startDate?: T;
        endDate?: T;
      };
  projectStatus?: T;
  beneficiaryMetrics?:
    | T
    | {
        metricName?: T;
        metricValue?: T;
        unitOrContext?: T;
        id?: T;
      };
  fundingAndSupport?:
    | T
    | {
        donorOrFunder?: T;
        grantDetails?: T;
      };
  heroMedia?: T;
  gallery?: T;
  outcomes?: T;
  reportsAndDocuments?: T;
  isFeatured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  eventType?: T;
  format?: T;
  schedule?:
    | T
    | {
        startDateTime?: T;
        endDateTime?: T;
        timezone?: T;
      };
  venue?:
    | T
    | {
        venueName?: T;
        address?: T;
        city?: T;
        country?: T;
      };
  onlineAccess?:
    | T
    | {
        meetingUrl?: T;
        accessInstructions?: T;
      };
  speakers?: T;
  partners?: T;
  relatedProgramme?: T;
  relatedProject?: T;
  heroMedia?: T;
  gallery?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories_select".
 */
export interface SuccessStoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  beneficiaryName?: T;
  beneficiaryRole?: T;
  location?: T;
  relatedProgramme?: T;
  relatedProject?: T;
  quote?: T;
  summary?: T;
  fullStory?: T;
  heroMedia?: T;
  gallery?: T;
  impactMetrics?:
    | T
    | {
        metricValue?: T;
        metricLabel?: T;
        id?: T;
      };
  storyDate?: T;
  isFeatured?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  authors?: T;
  category?: T;
  publishedAt?: T;
  heroMedia?: T;
  relatedProgrammes?: T;
  relatedProjects?: T;
  relatedEvents?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brand: {
    brandName: string;
    legalName: string;
    tagline?: string | null;
    /**
     * A global development organization originating from Nigeria.
     */
    organizationOrigin?: string | null;
    founderStorytelling?: string | null;
  };
  contact?: {
    generalEmail?: string | null;
    admissionsEmail?: string | null;
    partnershipsEmail?: string | null;
    phoneNumber?: string | null;
    headquartersAddress?: string | null;
  };
  socialChannels?: {
    linkedin?: string | null;
    twitter?: string | null;
    instagram?: string | null;
    facebook?: string | null;
    youtube?: string | null;
  };
  /**
   * Configure search engine metadata, Open Graph preview, and indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50-60 characters. Appears in search results and browser tabs.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150-160 characters. Concise summary of the page for search snippets.
     */
    metaDescription?: string | null;
    /**
     * Recommended dimension: 1200 × 630 pixels.
     */
    metaImage?: (number | null) | Media;
    /**
     * Check to prevent web crawlers from indexing this item.
     */
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        brandName?: T;
        legalName?: T;
        tagline?: T;
        organizationOrigin?: T;
        founderStorytelling?: T;
      };
  contact?:
    | T
    | {
        generalEmail?: T;
        admissionsEmail?: T;
        partnershipsEmail?: T;
        phoneNumber?: T;
        headquartersAddress?: T;
      };
  socialChannels?:
    | T
    | {
        linkedin?: T;
        twitter?: T;
        instagram?: T;
        facebook?: T;
        youtube?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
