/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'staff-invitations': StaffInvitation;
    'audit-logs': AuditLog;
    media: Media;
    people: Person;
    partners: Partner;
    'focus-areas': FocusArea;
    programmes: Programme;
    projects: Project;
    events: Event;
    'success-stories': SuccessStory;
    articles: Article;
    'article-categories': ArticleCategory;
    tags: Tag;
    locations: Location;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'staff-invitations': StaffInvitationsSelect<false> | StaffInvitationsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'focus-areas': FocusAreasSelect<false> | FocusAreasSelect<true>;
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'success-stories': SuccessStoriesSelect<false> | SuccessStoriesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'article-categories': ArticleCategoriesSelect<false> | ArticleCategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents':
      PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    ('false' | 'none' | 'null') | false | null | ('en' | 'fr' | 'de') | ('en' | 'fr' | 'de')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'fr' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Internal staff identities, role assignments, account lifecycle, and administrative privileges.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * e.g. Founder & CEO, Lead TVET Facilitator, Communications Director.
   */
  jobTitle?: string | null;
  /**
   * Operational lifecycle state. Inactive, suspended, or disabled staff cannot authenticate.
   */
  status: 'active' | 'invited' | 'suspended' | 'disabled';
  /**
   * Assigned organizational governance roles. Super Administrator holds full system privileges.
   */
  roles: (
    | 'super_admin'
    | 'admin'
    | 'content_editor'
    | 'content_approver'
    | 'events_manager'
    | 'programmes_manager'
    | 'media_manager'
    | 'applications_manager'
    | 'commerce_manager'
    | 'communications_manager'
  )[];
  /**
   * Optional granular permission overrides. Reserved strictly for Super Administrator assignment.
   */
  directPermissions?:
    | (
        | 'articles.read'
        | 'articles.create'
        | 'articles.update'
        | 'articles.submit'
        | 'articles.approve'
        | 'articles.publish'
        | 'articles.archive'
        | 'articles.delete'
        | 'events.read'
        | 'events.create'
        | 'events.update'
        | 'events.submit'
        | 'events.approve'
        | 'events.publish'
        | 'events.archive'
        | 'events.delete'
        | 'programmes.read'
        | 'programmes.create'
        | 'programmes.update'
        | 'programmes.submit'
        | 'programmes.approve'
        | 'programmes.publish'
        | 'programmes.archive'
        | 'programmes.delete'
        | 'projects.read'
        | 'projects.create'
        | 'projects.update'
        | 'projects.submit'
        | 'projects.approve'
        | 'projects.publish'
        | 'projects.archive'
        | 'projects.delete'
        | 'success_stories.read'
        | 'success_stories.create'
        | 'success_stories.update'
        | 'success_stories.submit'
        | 'success_stories.approve'
        | 'success_stories.publish'
        | 'success_stories.archive'
        | 'success_stories.delete'
        | 'media.read'
        | 'media.create'
        | 'media.update'
        | 'media.delete'
        | 'people.read'
        | 'people.create'
        | 'people.update'
        | 'people.publish'
        | 'people.delete'
        | 'partners.read'
        | 'partners.create'
        | 'partners.update'
        | 'partners.publish'
        | 'partners.delete'
        | 'focus_areas.read'
        | 'focus_areas.create'
        | 'focus_areas.update'
        | 'focus_areas.delete'
        | 'locations.read'
        | 'locations.create'
        | 'locations.update'
        | 'locations.delete'
        | 'taxonomies.read'
        | 'taxonomies.create'
        | 'taxonomies.update'
        | 'taxonomies.delete'
        | 'users.read'
        | 'users.create'
        | 'users.invite'
        | 'users.update_roles'
        | 'users.suspend'
        | 'users.disable'
        | 'users.delete'
        | 'invitations.read'
        | 'invitations.create'
        | 'invitations.revoke'
        | 'invitations.resend'
        | 'audit.read'
        | 'settings.read'
        | 'settings.update'
      )[]
    | null;
  invitedAt?: string | null;
  activatedAt?: string | null;
  disabledAt?: string | null;
  lastLoginAt?: string | null;
  mustChangePassword?: boolean | null;
  /**
   * Configuration flag indicating this account will require MFA once TOTP enforcement is enabled in Phase 04+. Note: MFA enforcement is deferred.
   */
  mfaRequired?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Manage single-use, time-limited cryptographic onboarding invitations for staff.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff-invitations".
 */
export interface StaffInvitation {
  id: number;
  email: string;
  name: string;
  jobTitle?: string | null;
  roles: (
    | 'super_admin'
    | 'admin'
    | 'content_editor'
    | 'content_approver'
    | 'events_manager'
    | 'programmes_manager'
    | 'media_manager'
    | 'applications_manager'
    | 'commerce_manager'
    | 'communications_manager'
  )[];
  /**
   * One-way cryptographic hash of the active single-use invitation token.
   */
  tokenHash: string;
  status: 'pending' | 'accepted' | 'expired' | 'revoked';
  expiresAt: string;
  invitedBy?: (number | null) | User;
  acceptedAt?: string | null;
  revokedAt?: string | null;
  revokedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only, tamper-resistant administrative audit records capturing security and content changes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  /**
   * e.g. user.invited, user.suspended, article.published, invitation.revoked
   */
  action: string;
  /**
   * e.g. users, articles, staff-invitations, programmes
   */
  resourceType: string;
  resourceId?: string | null;
  actor?: (number | null) | User;
  /**
   * Subject of user administrative changes (e.g. role updates, suspension).
   */
  targetUser?: (number | null) | User;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  requestId?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Crucial for accessibility (WCAG 2.2 AA) and image SEO. Describe the visual content.
   */
  alt: string;
  /**
   * Descriptive title for internal search and media library organization.
   */
  title?: string | null;
  /**
   * Editorial caption displayed below the media item in stories and galleries.
   */
  caption?: string | null;
  mediaType?: ('image' | 'document' | 'video') | null;
  attribution?: {
    /**
     * Name of the photographer, agency, or originating source.
     */
    photographerOrSource?: string | null;
    /**
     * Rights constraints or creative license details.
     */
    copyrightNotes?: string | null;
  };
  /**
   * Geographic location where photo/video was captured (e.g., Benin City, Lagos, Abuja).
   */
  location?: string | null;
  /**
   * Historical date when the asset was originally captured.
   */
  dateCaptured?: string | null;
  /**
   * Relational topic tags for asset library indexing.
   */
  tags?: (number | Tag)[] | null;
  /**
   * Optional embedded video link for streamable assets.
   */
  externalVideoUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Lightweight topic keyword (e.g., UI/UX, Renewable Energy, Youth Development, Apprenticeships).
   */
  name: string;
  /**
   * Unique URL identifier. Auto-generated from "name" if not specified.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  fullName: string;
  /**
   * Unique URL identifier. Auto-generated from "fullName" if not specified.
   */
  slug?: string | null;
  /**
   * Official position (e.g., Founder & CEO, Lead Technical Instructor, Board Advisor).
   */
  role: string;
  organization?: string | null;
  /**
   * e.g., Executive Leadership, Technology & Innovation, TVET Programmes.
   */
  division?: string | null;
  profileImage?: (number | null) | Media;
  /**
   * Brief 2-3 sentence introductory biography for cards and speaker profiles.
   */
  shortBio?: string | null;
  /**
   * Comprehensive biographical and impact background.
   */
  fullBio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  primaryLocation?: (number | null) | Location;
  designations?: {
    isLeadership?: boolean | null;
    isBoardMember?: boolean | null;
    isTeamMember?: boolean | null;
    isFacilitator?: boolean | null;
    isSpeaker?: boolean | null;
    isAuthor?: boolean | null;
  };
  socialLinks?: {
    linkedin?: string | null;
    twitter?: string | null;
    instagram?: string | null;
    website?: string | null;
  };
  contactInfo?: {
    email?: string | null;
    showEmailPublicly?: boolean | null;
    phone?: string | null;
    showPhonePublicly?: boolean | null;
  };
  /**
   * Lower numbers appear first (e.g., 1 for Founder/CEO).
   */
  displayOrder?: number | null;
  status?: ('active' | 'alumni' | 'inactive') | null;
  /**
   * Configure search engine metadata, Open Graph previews, and web crawler indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters. Appears in search results and browser title bars. Falls back to entity title.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150–160 characters. Search result summary snippet. Falls back to short description/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute URL override. Leave empty to automatically use the standard canonical URL.
     */
    canonicalUrl?: string | null;
    /**
     * Custom title for social card sharing (Facebook, LinkedIn, Twitter/X). Falls back to Meta Title.
     */
    ogTitle?: string | null;
    /**
     * Custom summary for social card previews. Falls back to Meta Description.
     */
    ogDescription?: string | null;
    /**
     * Recommended resolution: 1200 × 630 pixels. Falls back to hero media or global brand card.
     */
    ogImage?: (number | null) | Media;
    /**
     * Check to instruct search engines NOT to display this page in search results.
     */
    noIndex?: boolean | null;
    /**
     * Check to instruct search crawlers NOT to crawl links on this page.
     */
    noFollow?: boolean | null;
    /**
     * Optional raw JSON-LD schema override for advanced schema customization.
     */
    customJsonLd?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  /**
   * e.g., Genius Hub Headquarters, Edo Innovation Center, Lagos Training Hub.
   */
  name: string;
  /**
   * Unique URL identifier. Auto-generated from "name" if not specified.
   */
  slug?: string | null;
  locationType:
    | 'hub_facility'
    | 'office'
    | 'training_center'
    | 'community_venue'
    | 'partner_facility'
    | 'other';
  /**
   * Physical street address if applicable (not required for all field venues).
   */
  address?: string | null;
  city: string;
  stateOrRegion: string;
  country: string;
  coordinates?: {
    latitude?: number | null;
    longitude?: number | null;
  };
  flags?: {
    isOffice?: boolean | null;
    isProgrammeLocation?: boolean | null;
    isEventVenue?: boolean | null;
  };
  contactInfo?: {
    phone?: string | null;
    email?: string | null;
  };
  /**
   * e.g., Mon–Fri: 8:30 AM – 5:00 PM, Sat: 9:00 AM – 2:00 PM.
   */
  openingHours?: string | null;
  mapDisplay?: boolean | null;
  /**
   * When checked, generates a public route and renders SEO metadata.
   */
  isPublicPageEnabled?: boolean | null;
  /**
   * Configure search engine metadata, Open Graph previews, and web crawler indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters. Appears in search results and browser title bars. Falls back to entity title.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150–160 characters. Search result summary snippet. Falls back to short description/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute URL override. Leave empty to automatically use the standard canonical URL.
     */
    canonicalUrl?: string | null;
    /**
     * Custom title for social card sharing (Facebook, LinkedIn, Twitter/X). Falls back to Meta Title.
     */
    ogTitle?: string | null;
    /**
     * Custom summary for social card previews. Falls back to Meta Description.
     */
    ogDescription?: string | null;
    /**
     * Recommended resolution: 1200 × 630 pixels. Falls back to hero media or global brand card.
     */
    ogImage?: (number | null) | Media;
    /**
     * Check to instruct search engines NOT to display this page in search results.
     */
    noIndex?: boolean | null;
    /**
     * Check to instruct search crawlers NOT to crawl links on this page.
     */
    noFollow?: boolean | null;
    /**
     * Optional raw JSON-LD schema override for advanced schema customization.
     */
    customJsonLd?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  /**
   * Unique URL identifier. Auto-generated from "name" if not specified.
   */
  slug?: string | null;
  /**
   * Transparent PNG or SVG logo preferred.
   */
  logo: number | Media;
  website?: string | null;
  partnerType:
    | 'international_development'
    | 'donor'
    | 'government'
    | 'ngo'
    | 'corporate'
    | 'academic_research'
    | 'investor'
    | 'media'
    | 'community_organization'
    | 'other';
  relationshipType?:
    | (
        | 'strategic_partner'
        | 'funding_partner'
        | 'implementing_partner'
        | 'technical_partner'
        | 'ecosystem_partner'
      )
    | null;
  /**
   * Brief overview of the partnership collaboration and institutional synergy.
   */
  description?: string | null;
  timeline?: {
    startYear?: number | null;
    endYear?: number | null;
  };
  isFeatured?: boolean | null;
  /**
   * Configure search engine metadata, Open Graph previews, and web crawler indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters. Appears in search results and browser title bars. Falls back to entity title.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150–160 characters. Search result summary snippet. Falls back to short description/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute URL override. Leave empty to automatically use the standard canonical URL.
     */
    canonicalUrl?: string | null;
    /**
     * Custom title for social card sharing (Facebook, LinkedIn, Twitter/X). Falls back to Meta Title.
     */
    ogTitle?: string | null;
    /**
     * Custom summary for social card previews. Falls back to Meta Description.
     */
    ogDescription?: string | null;
    /**
     * Recommended resolution: 1200 × 630 pixels. Falls back to hero media or global brand card.
     */
    ogImage?: (number | null) | Media;
    /**
     * Check to instruct search engines NOT to display this page in search results.
     */
    noIndex?: boolean | null;
    /**
     * Check to instruct search crawlers NOT to crawl links on this page.
     */
    noFollow?: boolean | null;
    /**
     * Optional raw JSON-LD schema override for advanced schema customization.
     */
    customJsonLd?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "focus-areas".
 */
export interface FocusArea {
  id: number;
  /**
   * Strategic development pillar (e.g., Digital Skills & Technology, TVET & Vocational Mastery, Enterprise Incubation, Migration Reintegration).
   */
  title: string;
  /**
   * Unique URL identifier. Auto-generated from "title" if not specified.
   */
  slug?: string | null;
  /**
   * Comprehensive overview of the developmental rationale, objectives, and impact.
   */
  description?: string | null;
  /**
   * SVG or transparent PNG icon representing this focus area.
   */
  icon?: (number | null) | Media;
  heroMedia?: (number | null) | Media;
  displayOrder?: number | null;
  isFeatured?: boolean | null;
  /**
   * Configure search engine metadata, Open Graph previews, and web crawler indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters. Appears in search results and browser title bars. Falls back to entity title.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150–160 characters. Search result summary snippet. Falls back to short description/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute URL override. Leave empty to automatically use the standard canonical URL.
     */
    canonicalUrl?: string | null;
    /**
     * Custom title for social card sharing (Facebook, LinkedIn, Twitter/X). Falls back to Meta Title.
     */
    ogTitle?: string | null;
    /**
     * Custom summary for social card previews. Falls back to Meta Description.
     */
    ogDescription?: string | null;
    /**
     * Recommended resolution: 1200 × 630 pixels. Falls back to hero media or global brand card.
     */
    ogImage?: (number | null) | Media;
    /**
     * Check to instruct search engines NOT to display this page in search results.
     */
    noIndex?: boolean | null;
    /**
     * Check to instruct search crawlers NOT to crawl links on this page.
     */
    noFollow?: boolean | null;
    /**
     * Optional raw JSON-LD schema override for advanced schema customization.
     */
    customJsonLd?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes".
 */
export interface Programme {
  id: number;
  title: string;
  /**
   * Unique URL identifier. Auto-generated from "title" if not specified.
   */
  slug?: string | null;
  /**
   * Concise summary for programme cards, catalogue views, and search previews.
   */
  shortDescription: string;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Authoritative topical pillar mapping for categorization and SEO.
   */
  focusAreas: (number | FocusArea)[];
  /**
   * e.g., Unemployed youth, returning migrants, female entrepreneurs, tech enthusiasts.
   */
  targetAudience?: string | null;
  deliveryFormat?: ('in_person' | 'virtual' | 'hybrid') | null;
  /**
   * Structured relationship to verified physical hubs and campuses.
   */
  locations?: (number | Location)[] | null;
  schedule?: {
    startDate?: string | null;
    endDate?: string | null;
    isOngoing?: boolean | null;
  };
  applicationStatus?: ('open' | 'upcoming' | 'closed' | 'by_invitation') | null;
  /**
   * Internal registration route or external portal endpoint.
   */
  applicationUrl?: string | null;
  heroMedia?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  partners?: (number | Partner)[] | null;
  tags?: (number | Tag)[] | null;
  impactStatistics?:
    | {
        metricValue: string;
        metricLabel: string;
        metricDescription?: string | null;
        id?: string | null;
      }[]
    | null;
  isFeatured?: boolean | null;
  status: 'draft' | 'in_review' | 'changes_requested' | 'approved' | 'published' | 'archived';
  workflow?: {
    /**
     * Timestamp when this document was submitted for review.
     */
    submittedAt?: string | null;
    /**
     * Staff member who submitted this document for review.
     */
    submittedBy?: (number | null) | User;
    /**
     * Timestamp when this document was formally approved.
     */
    approvedAt?: string | null;
    /**
     * Staff reviewer who approved this document.
     */
    approvedBy?: (number | null) | User;
    /**
     * Timestamp when this document was published to the public website.
     */
    publishedAt?: string | null;
    /**
     * Staff member who executed publication.
     */
    publishedBy?: (number | null) | User;
    /**
     * Internal notes, revision requests, or editorial guidance for the author.
     */
    reviewNotes?: string | null;
  };
  /**
   * Configure search engine metadata, Open Graph previews, and web crawler indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters. Appears in search results and browser title bars. Falls back to entity title.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150–160 characters. Search result summary snippet. Falls back to short description/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute URL override. Leave empty to automatically use the standard canonical URL.
     */
    canonicalUrl?: string | null;
    /**
     * Custom title for social card sharing (Facebook, LinkedIn, Twitter/X). Falls back to Meta Title.
     */
    ogTitle?: string | null;
    /**
     * Custom summary for social card previews. Falls back to Meta Description.
     */
    ogDescription?: string | null;
    /**
     * Recommended resolution: 1200 × 630 pixels. Falls back to hero media or global brand card.
     */
    ogImage?: (number | null) | Media;
    /**
     * Check to instruct search engines NOT to display this page in search results.
     */
    noIndex?: boolean | null;
    /**
     * Check to instruct search crawlers NOT to crawl links on this page.
     */
    noFollow?: boolean | null;
    /**
     * Optional raw JSON-LD schema override for advanced schema customization.
     */
    customJsonLd?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Unique URL identifier. Auto-generated from "title" if not specified.
   */
  slug?: string | null;
  /**
   * Concise summary of the intervention, target beneficiaries, and overarching purpose.
   */
  summary: string;
  fullContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The broader institutional programme this specific project operationalizes.
   */
  parentProgramme?: (number | null) | Programme;
  focusAreas?: (number | FocusArea)[] | null;
  partners?: (number | Partner)[] | null;
  locations?: (number | Location)[] | null;
  timeline?: {
    startDate?: string | null;
    endDate?: string | null;
  };
  projectStatus?: ('planned' | 'active' | 'completed' | 'on_hold') | null;
  beneficiaryMetrics?:
    | {
        metricName: string;
        metricValue: string;
        unitOrContext?: string | null;
        id?: string | null;
      }[]
    | null;
  fundingAndSupport?: {
    donorOrFunder?: string | null;
    grantDetails?: string | null;
  };
  tags?: (number | Tag)[] | null;
  heroMedia?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  outcomes?: string | null;
  reportsAndDocuments?: (number | Media)[] | null;
  isFeatured?: boolean | null;
  status: 'draft' | 'in_review' | 'changes_requested' | 'approved' | 'published' | 'archived';
  workflow?: {
    /**
     * Timestamp when this document was submitted for review.
     */
    submittedAt?: string | null;
    /**
     * Staff member who submitted this document for review.
     */
    submittedBy?: (number | null) | User;
    /**
     * Timestamp when this document was formally approved.
     */
    approvedAt?: string | null;
    /**
     * Staff reviewer who approved this document.
     */
    approvedBy?: (number | null) | User;
    /**
     * Timestamp when this document was published to the public website.
     */
    publishedAt?: string | null;
    /**
     * Staff member who executed publication.
     */
    publishedBy?: (number | null) | User;
    /**
     * Internal notes, revision requests, or editorial guidance for the author.
     */
    reviewNotes?: string | null;
  };
  /**
   * Configure search engine metadata, Open Graph previews, and web crawler indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters. Appears in search results and browser title bars. Falls back to entity title.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150–160 characters. Search result summary snippet. Falls back to short description/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute URL override. Leave empty to automatically use the standard canonical URL.
     */
    canonicalUrl?: string | null;
    /**
     * Custom title for social card sharing (Facebook, LinkedIn, Twitter/X). Falls back to Meta Title.
     */
    ogTitle?: string | null;
    /**
     * Custom summary for social card previews. Falls back to Meta Description.
     */
    ogDescription?: string | null;
    /**
     * Recommended resolution: 1200 × 630 pixels. Falls back to hero media or global brand card.
     */
    ogImage?: (number | null) | Media;
    /**
     * Check to instruct search engines NOT to display this page in search results.
     */
    noIndex?: boolean | null;
    /**
     * Check to instruct search crawlers NOT to crawl links on this page.
     */
    noFollow?: boolean | null;
    /**
     * Optional raw JSON-LD schema override for advanced schema customization.
     */
    customJsonLd?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Unique URL identifier. Auto-generated from "title" if not specified.
   */
  slug?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  eventType:
    | 'workshop'
    | 'summit'
    | 'hackathon'
    | 'exhibition'
    | 'webinar'
    | 'meetup'
    | 'ceremony'
    | 'other';
  format?: ('in_person' | 'virtual' | 'hybrid') | null;
  schedule: {
    startDateTime: string;
    endDateTime?: string | null;
    timezone?: string | null;
  };
  /**
   * Structured link to verified physical facility or innovation center.
   */
  venueLocation?: (number | null) | Location;
  /**
   * e.g., Main Auditorium, Hall B, 3rd Floor.
   */
  customVenueNotes?: string | null;
  onlineAccess?: {
    meetingUrl?: string | null;
    accessInstructions?: string | null;
  };
  focusAreas?: (number | FocusArea)[] | null;
  speakers?: (number | Person)[] | null;
  partners?: (number | Partner)[] | null;
  tags?: (number | Tag)[] | null;
  relatedProgramme?: (number | null) | Programme;
  relatedProject?: (number | null) | Project;
  heroMedia?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  status: 'draft' | 'in_review' | 'changes_requested' | 'approved' | 'published' | 'archived';
  workflow?: {
    /**
     * Timestamp when this document was submitted for review.
     */
    submittedAt?: string | null;
    /**
     * Staff member who submitted this document for review.
     */
    submittedBy?: (number | null) | User;
    /**
     * Timestamp when this document was formally approved.
     */
    approvedAt?: string | null;
    /**
     * Staff reviewer who approved this document.
     */
    approvedBy?: (number | null) | User;
    /**
     * Timestamp when this document was published to the public website.
     */
    publishedAt?: string | null;
    /**
     * Staff member who executed publication.
     */
    publishedBy?: (number | null) | User;
    /**
     * Internal notes, revision requests, or editorial guidance for the author.
     */
    reviewNotes?: string | null;
  };
  /**
   * Configure search engine metadata, Open Graph previews, and web crawler indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters. Appears in search results and browser title bars. Falls back to entity title.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150–160 characters. Search result summary snippet. Falls back to short description/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute URL override. Leave empty to automatically use the standard canonical URL.
     */
    canonicalUrl?: string | null;
    /**
     * Custom title for social card sharing (Facebook, LinkedIn, Twitter/X). Falls back to Meta Title.
     */
    ogTitle?: string | null;
    /**
     * Custom summary for social card previews. Falls back to Meta Description.
     */
    ogDescription?: string | null;
    /**
     * Recommended resolution: 1200 × 630 pixels. Falls back to hero media or global brand card.
     */
    ogImage?: (number | null) | Media;
    /**
     * Check to instruct search engines NOT to display this page in search results.
     */
    noIndex?: boolean | null;
    /**
     * Check to instruct search crawlers NOT to crawl links on this page.
     */
    noFollow?: boolean | null;
    /**
     * Optional raw JSON-LD schema override for advanced schema customization.
     */
    customJsonLd?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories".
 */
export interface SuccessStory {
  id: number;
  /**
   * Compelling headline (e.g., "From Unemployed Graduate to Leading UI/UX Designer in Edo State").
   */
  title: string;
  /**
   * Unique URL identifier. Auto-generated from "title" if not specified.
   */
  slug?: string | null;
  beneficiaryName: string;
  /**
   * e.g., Founder at StitchLab Hub, Junior Software Engineer at TechCorp.
   */
  beneficiaryRole?: string | null;
  location?: (number | null) | Location;
  focusAreas?: (number | FocusArea)[] | null;
  relatedProgramme?: (number | null) | Programme;
  relatedProject?: (number | null) | Project;
  /**
   * Highlighted pull-quote for impact cards and hero showcases.
   */
  quote?: string | null;
  summary?: string | null;
  fullStory?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tags?: (number | Tag)[] | null;
  heroMedia?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  impactMetrics?:
    | {
        metricValue: string;
        metricLabel: string;
        id?: string | null;
      }[]
    | null;
  storyDate?: string | null;
  isFeatured?: boolean | null;
  status: 'draft' | 'in_review' | 'changes_requested' | 'approved' | 'published' | 'archived';
  workflow?: {
    /**
     * Timestamp when this document was submitted for review.
     */
    submittedAt?: string | null;
    /**
     * Staff member who submitted this document for review.
     */
    submittedBy?: (number | null) | User;
    /**
     * Timestamp when this document was formally approved.
     */
    approvedAt?: string | null;
    /**
     * Staff reviewer who approved this document.
     */
    approvedBy?: (number | null) | User;
    /**
     * Timestamp when this document was published to the public website.
     */
    publishedAt?: string | null;
    /**
     * Staff member who executed publication.
     */
    publishedBy?: (number | null) | User;
    /**
     * Internal notes, revision requests, or editorial guidance for the author.
     */
    reviewNotes?: string | null;
  };
  /**
   * Configure search engine metadata, Open Graph previews, and web crawler indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters. Appears in search results and browser title bars. Falls back to entity title.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150–160 characters. Search result summary snippet. Falls back to short description/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute URL override. Leave empty to automatically use the standard canonical URL.
     */
    canonicalUrl?: string | null;
    /**
     * Custom title for social card sharing (Facebook, LinkedIn, Twitter/X). Falls back to Meta Title.
     */
    ogTitle?: string | null;
    /**
     * Custom summary for social card previews. Falls back to Meta Description.
     */
    ogDescription?: string | null;
    /**
     * Recommended resolution: 1200 × 630 pixels. Falls back to hero media or global brand card.
     */
    ogImage?: (number | null) | Media;
    /**
     * Check to instruct search engines NOT to display this page in search results.
     */
    noIndex?: boolean | null;
    /**
     * Check to instruct search crawlers NOT to crawl links on this page.
     */
    noFollow?: boolean | null;
    /**
     * Optional raw JSON-LD schema override for advanced schema customization.
     */
    customJsonLd?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Unique URL identifier. Auto-generated from "title" if not specified.
   */
  slug?: string | null;
  /**
   * Short teaser displayed in news grids, newsletters, and search snippets.
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Structured relationship to controlled editorial categories.
   */
  category: number | ArticleCategory;
  focusAreas?: (number | FocusArea)[] | null;
  tags?: (number | Tag)[] | null;
  authors?: (number | Person)[] | null;
  publishedAt?: string | null;
  heroMedia?: (number | null) | Media;
  relatedProgrammes?: (number | Programme)[] | null;
  relatedProjects?: (number | Project)[] | null;
  relatedEvents?: (number | Event)[] | null;
  status: 'draft' | 'in_review' | 'changes_requested' | 'approved' | 'published' | 'archived';
  workflow?: {
    /**
     * Timestamp when this document was submitted for review.
     */
    submittedAt?: string | null;
    /**
     * Staff member who submitted this document for review.
     */
    submittedBy?: (number | null) | User;
    /**
     * Timestamp when this document was formally approved.
     */
    approvedAt?: string | null;
    /**
     * Staff reviewer who approved this document.
     */
    approvedBy?: (number | null) | User;
    /**
     * Timestamp when this document was published to the public website.
     */
    publishedAt?: string | null;
    /**
     * Staff member who executed publication.
     */
    publishedBy?: (number | null) | User;
    /**
     * Internal notes, revision requests, or editorial guidance for the author.
     */
    reviewNotes?: string | null;
  };
  /**
   * Configure search engine metadata, Open Graph previews, and web crawler indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters. Appears in search results and browser title bars. Falls back to entity title.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150–160 characters. Search result summary snippet. Falls back to short description/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute URL override. Leave empty to automatically use the standard canonical URL.
     */
    canonicalUrl?: string | null;
    /**
     * Custom title for social card sharing (Facebook, LinkedIn, Twitter/X). Falls back to Meta Title.
     */
    ogTitle?: string | null;
    /**
     * Custom summary for social card previews. Falls back to Meta Description.
     */
    ogDescription?: string | null;
    /**
     * Recommended resolution: 1200 × 630 pixels. Falls back to hero media or global brand card.
     */
    ogImage?: (number | null) | Media;
    /**
     * Check to instruct search engines NOT to display this page in search results.
     */
    noIndex?: boolean | null;
    /**
     * Check to instruct search crawlers NOT to crawl links on this page.
     */
    noFollow?: boolean | null;
    /**
     * Optional raw JSON-LD schema override for advanced schema customization.
     */
    customJsonLd?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-categories".
 */
export interface ArticleCategory {
  id: number;
  /**
   * e.g., Insights & Thought Leadership, Corporate News, Field Dispatches, Policy Research.
   */
  name: string;
  /**
   * Unique URL identifier. Auto-generated from "name" if not specified.
   */
  slug?: string | null;
  description?: string | null;
  displayOrder?: number | null;
  /**
   * Configure search engine metadata, Open Graph previews, and web crawler indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters. Appears in search results and browser title bars. Falls back to entity title.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150–160 characters. Search result summary snippet. Falls back to short description/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute URL override. Leave empty to automatically use the standard canonical URL.
     */
    canonicalUrl?: string | null;
    /**
     * Custom title for social card sharing (Facebook, LinkedIn, Twitter/X). Falls back to Meta Title.
     */
    ogTitle?: string | null;
    /**
     * Custom summary for social card previews. Falls back to Meta Description.
     */
    ogDescription?: string | null;
    /**
     * Recommended resolution: 1200 × 630 pixels. Falls back to hero media or global brand card.
     */
    ogImage?: (number | null) | Media;
    /**
     * Check to instruct search engines NOT to display this page in search results.
     */
    noIndex?: boolean | null;
    /**
     * Check to instruct search crawlers NOT to crawl links on this page.
     */
    noFollow?: boolean | null;
    /**
     * Optional raw JSON-LD schema override for advanced schema customization.
     */
    customJsonLd?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'staff-invitations';
        value: number | StaffInvitation;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'focus-areas';
        value: number | FocusArea;
      } | null)
    | ({
        relationTo: 'programmes';
        value: number | Programme;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'success-stories';
        value: number | SuccessStory;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'article-categories';
        value: number | ArticleCategory;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  jobTitle?: T;
  status?: T;
  roles?: T;
  directPermissions?: T;
  invitedAt?: T;
  activatedAt?: T;
  disabledAt?: T;
  lastLoginAt?: T;
  mustChangePassword?: T;
  mfaRequired?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff-invitations_select".
 */
export interface StaffInvitationsSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  jobTitle?: T;
  roles?: T;
  tokenHash?: T;
  status?: T;
  expiresAt?: T;
  invitedBy?: T;
  acceptedAt?: T;
  revokedAt?: T;
  revokedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  resourceType?: T;
  resourceId?: T;
  actor?: T;
  targetUser?: T;
  before?: T;
  after?: T;
  metadata?: T;
  ipAddress?: T;
  userAgent?: T;
  requestId?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  title?: T;
  caption?: T;
  mediaType?: T;
  attribution?:
    | T
    | {
        photographerOrSource?: T;
        copyrightNotes?: T;
      };
  location?: T;
  dateCaptured?: T;
  tags?: T;
  externalVideoUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  fullName?: T;
  slug?: T;
  role?: T;
  organization?: T;
  division?: T;
  profileImage?: T;
  shortBio?: T;
  fullBio?: T;
  primaryLocation?: T;
  designations?:
    | T
    | {
        isLeadership?: T;
        isBoardMember?: T;
        isTeamMember?: T;
        isFacilitator?: T;
        isSpeaker?: T;
        isAuthor?: T;
      };
  socialLinks?:
    | T
    | {
        linkedin?: T;
        twitter?: T;
        instagram?: T;
        website?: T;
      };
  contactInfo?:
    | T
    | {
        email?: T;
        showEmailPublicly?: T;
        phone?: T;
        showPhonePublicly?: T;
      };
  displayOrder?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noIndex?: T;
        noFollow?: T;
        customJsonLd?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  website?: T;
  partnerType?: T;
  relationshipType?: T;
  description?: T;
  timeline?:
    | T
    | {
        startYear?: T;
        endYear?: T;
      };
  isFeatured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noIndex?: T;
        noFollow?: T;
        customJsonLd?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "focus-areas_select".
 */
export interface FocusAreasSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  icon?: T;
  heroMedia?: T;
  displayOrder?: T;
  isFeatured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noIndex?: T;
        noFollow?: T;
        customJsonLd?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  fullDescription?: T;
  focusAreas?: T;
  targetAudience?: T;
  deliveryFormat?: T;
  locations?: T;
  schedule?:
    | T
    | {
        startDate?: T;
        endDate?: T;
        isOngoing?: T;
      };
  applicationStatus?: T;
  applicationUrl?: T;
  heroMedia?: T;
  gallery?: T;
  partners?: T;
  tags?: T;
  impactStatistics?:
    | T
    | {
        metricValue?: T;
        metricLabel?: T;
        metricDescription?: T;
        id?: T;
      };
  isFeatured?: T;
  status?: T;
  workflow?:
    | T
    | {
        submittedAt?: T;
        submittedBy?: T;
        approvedAt?: T;
        approvedBy?: T;
        publishedAt?: T;
        publishedBy?: T;
        reviewNotes?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noIndex?: T;
        noFollow?: T;
        customJsonLd?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  fullContent?: T;
  parentProgramme?: T;
  focusAreas?: T;
  partners?: T;
  locations?: T;
  timeline?:
    | T
    | {
        startDate?: T;
        endDate?: T;
      };
  projectStatus?: T;
  beneficiaryMetrics?:
    | T
    | {
        metricName?: T;
        metricValue?: T;
        unitOrContext?: T;
        id?: T;
      };
  fundingAndSupport?:
    | T
    | {
        donorOrFunder?: T;
        grantDetails?: T;
      };
  tags?: T;
  heroMedia?: T;
  gallery?: T;
  outcomes?: T;
  reportsAndDocuments?: T;
  isFeatured?: T;
  status?: T;
  workflow?:
    | T
    | {
        submittedAt?: T;
        submittedBy?: T;
        approvedAt?: T;
        approvedBy?: T;
        publishedAt?: T;
        publishedBy?: T;
        reviewNotes?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noIndex?: T;
        noFollow?: T;
        customJsonLd?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  eventType?: T;
  format?: T;
  schedule?:
    | T
    | {
        startDateTime?: T;
        endDateTime?: T;
        timezone?: T;
      };
  venueLocation?: T;
  customVenueNotes?: T;
  onlineAccess?:
    | T
    | {
        meetingUrl?: T;
        accessInstructions?: T;
      };
  focusAreas?: T;
  speakers?: T;
  partners?: T;
  tags?: T;
  relatedProgramme?: T;
  relatedProject?: T;
  heroMedia?: T;
  gallery?: T;
  status?: T;
  workflow?:
    | T
    | {
        submittedAt?: T;
        submittedBy?: T;
        approvedAt?: T;
        approvedBy?: T;
        publishedAt?: T;
        publishedBy?: T;
        reviewNotes?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noIndex?: T;
        noFollow?: T;
        customJsonLd?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories_select".
 */
export interface SuccessStoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  beneficiaryName?: T;
  beneficiaryRole?: T;
  location?: T;
  focusAreas?: T;
  relatedProgramme?: T;
  relatedProject?: T;
  quote?: T;
  summary?: T;
  fullStory?: T;
  tags?: T;
  heroMedia?: T;
  gallery?: T;
  impactMetrics?:
    | T
    | {
        metricValue?: T;
        metricLabel?: T;
        id?: T;
      };
  storyDate?: T;
  isFeatured?: T;
  status?: T;
  workflow?:
    | T
    | {
        submittedAt?: T;
        submittedBy?: T;
        approvedAt?: T;
        approvedBy?: T;
        publishedAt?: T;
        publishedBy?: T;
        reviewNotes?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noIndex?: T;
        noFollow?: T;
        customJsonLd?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  focusAreas?: T;
  tags?: T;
  authors?: T;
  publishedAt?: T;
  heroMedia?: T;
  relatedProgrammes?: T;
  relatedProjects?: T;
  relatedEvents?: T;
  status?: T;
  workflow?:
    | T
    | {
        submittedAt?: T;
        submittedBy?: T;
        approvedAt?: T;
        approvedBy?: T;
        publishedAt?: T;
        publishedBy?: T;
        reviewNotes?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noIndex?: T;
        noFollow?: T;
        customJsonLd?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-categories_select".
 */
export interface ArticleCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  displayOrder?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noIndex?: T;
        noFollow?: T;
        customJsonLd?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  locationType?: T;
  address?: T;
  city?: T;
  stateOrRegion?: T;
  country?: T;
  coordinates?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  flags?:
    | T
    | {
        isOffice?: T;
        isProgrammeLocation?: T;
        isEventVenue?: T;
      };
  contactInfo?:
    | T
    | {
        phone?: T;
        email?: T;
      };
  openingHours?: T;
  mapDisplay?: T;
  isPublicPageEnabled?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noIndex?: T;
        noFollow?: T;
        customJsonLd?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brand: {
    brandName: string;
    legalName: string;
    tagline?: string | null;
    /**
     * A global development organization originating from Nigeria.
     */
    organizationOrigin?: string | null;
    founderStorytelling?: string | null;
  };
  contact?: {
    generalEmail?: string | null;
    admissionsEmail?: string | null;
    partnershipsEmail?: string | null;
    phoneNumber?: string | null;
    headquartersAddress?: string | null;
  };
  socialChannels?: {
    linkedin?: string | null;
    twitter?: string | null;
    instagram?: string | null;
    facebook?: string | null;
    youtube?: string | null;
  };
  /**
   * Configure search engine metadata, Open Graph previews, and web crawler indexing controls.
   */
  seo?: {
    /**
     * Recommended: 50–60 characters. Appears in search results and browser title bars. Falls back to entity title.
     */
    metaTitle?: string | null;
    /**
     * Recommended: 150–160 characters. Search result summary snippet. Falls back to short description/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute URL override. Leave empty to automatically use the standard canonical URL.
     */
    canonicalUrl?: string | null;
    /**
     * Custom title for social card sharing (Facebook, LinkedIn, Twitter/X). Falls back to Meta Title.
     */
    ogTitle?: string | null;
    /**
     * Custom summary for social card previews. Falls back to Meta Description.
     */
    ogDescription?: string | null;
    /**
     * Recommended resolution: 1200 × 630 pixels. Falls back to hero media or global brand card.
     */
    ogImage?: (number | null) | Media;
    /**
     * Check to instruct search engines NOT to display this page in search results.
     */
    noIndex?: boolean | null;
    /**
     * Check to instruct search crawlers NOT to crawl links on this page.
     */
    noFollow?: boolean | null;
    /**
     * Optional raw JSON-LD schema override for advanced schema customization.
     */
    customJsonLd?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        brandName?: T;
        legalName?: T;
        tagline?: T;
        organizationOrigin?: T;
        founderStorytelling?: T;
      };
  contact?:
    | T
    | {
        generalEmail?: T;
        admissionsEmail?: T;
        partnershipsEmail?: T;
        phoneNumber?: T;
        headquartersAddress?: T;
      };
  socialChannels?:
    | T
    | {
        linkedin?: T;
        twitter?: T;
        instagram?: T;
        facebook?: T;
        youtube?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        noIndex?: T;
        noFollow?: T;
        customJsonLd?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
